#!/bin/bash

echo "Adding ChineseSentenceDetector.swift to Xcode project"
echo ""
echo "FILE TO ADD:"
echo "============"
echo "ChineseSentenceDetector.swift"
echo "Location: Snapzify/Utils/ChineseSentenceDetector.swift"
echo ""
echo "TO ADD THIS FILE:"
echo "================="
echo "1. Open Snapzify.xcodeproj in Xcode"
echo "2. Right-click on the 'Utils' group in the project navigator"
echo "3. Select 'Add Files to Snapzify...'"
echo "4. Navigate to Snapzify/Utils/"
echo "5. Select ChineseSentenceDetector.swift"
echo "6. Make sure 'Copy items if needed' is UNCHECKED"
echo "7. Make sure 'Snapzify' target is CHECKED"
echo "8. Click 'Add'"
echo ""
echo "After adding, rebuild the project."
